all:
	g++  Video.cpp main.cpp  -I/home/adrian/opencv/include/opencv2/ -L/home/adrian/opencv/build/lib/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -o vision.bin
run:
	./vision.bin


